project:
  type: book
  output-dir: _book

book:
  title: "Outils de recherche en sciences sociales numériques"
  reader-mode: true

  page-footer:
    left: |
      Livre-outils
    right: |
      Ce livre a été écrit avec <a href="https://quarto.org/">Quarto</a>.
  cover-image: images/logo_CLESSN_inverse.png
  favicon: images/logo_CLESSN_inverse.png
  repo-url: https://github.com/clessn/livre-outils
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - chapitre_1.qmd
    - chapitre_2.qmd
    - chapitre_3.qmd
    - chapitre_4.qmd
    - chapitre_5.qmd
    - chapitre_6.qmd
    - chapitre_7.qmd
    - chapitre_8.qmd
    - conclusion.qmd
    - references.qmd

bibliography: livre-outils.bib
csl: https://www.zotero.org/styles/apa
citations-hover: true
citeproc: true

lang: fr_CA

format:
  html:
    theme:
      light: pulse
      dark: slate
    code-link: true
    code-copy: true

    author-meta: "Chaire de leadership en enseignement des sciences sociales numériques (CLESSN)"
    callout-appearance: simple

editor: visual