project:
  type: book
  output-dir: book

book:
  title: "Outils de recherche en sciences sociales numériques"
  author: "Chaire de leadership en enseignement des sciences sociales numériques (CLESSN)"
  date: today
  chapters:
    - index.qmd
    - chapitre_1.qmd
    - chapitre_2.qmd
    - chapitre_3.qmd
    - chapitre_4.qmd
    - chapitre_5.qmd
    - chapitre_6.qmd
    - chapitre_7.qmd
    - chapitre_8.qmd
    - chapitre_9.qmd
    - chapitre10.qmd
    - references.qmd

bibliography: livre-outils.bib

format:
  pdf:
    documentclass: scrbook

editor: visual

